config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      get 'favourite_api/create'
      get 'favourite_api/destroy'
      get 'favourite_api/show'
      get 'favourite_api/index'

      get 'fizzbuzz_api/show'
    end
  end

  resources :favourites
  root to: 'favourites#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
end

app/controllers/api/v1/favourite_api_controller.rb
class Api::V1::FavouriteApiController < ApplicationController

  def create

    @favourite = Favourite.new(fnumber:favourite_params[:fnumber])

    if !@favourite.nil?
      @favourite.save
      render json: @favourite.to_json, status:200
    else
      render json: {error:"Favourite could not be created"} , status:422
    end

  end

  def destroy

    @favourite = Favourite.all.find_by(fnumber:favourite_params[:fnumber])

    if !@favourite.nil?
      @favourite.destroy
      render json: {sucesss:"Favourite number #{favourite_params[:fnumber]} deleted" }, status: 200
    else
      render json: {error:"Favourite could not be deleted"} , status:422
    end

  end

  def show

    @favourite = Favourite.where(fnumber:favourite_params[:fnumber])

    render json: @favourite.to_json, status:200

  end

  def index

    render json: Favourite.all.to_json, status:200

  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def favourite_params
    params.permit(:fnumber)
  end

end

app/controllers/api/v1/fizzbuzz_api_controller.rb
class Api::V1::FizzbuzzApiController < ApplicationController
  require 'fizzbuzz'

  # Set defaults for fizzBuzz
  RESUTLSPERPAGE = 100
  HIGHESTNUMBER = 100_000_000_000
  def show
    fizzBuzzObj = FizzBuzz.new

    # Parameterized loading or default settings
    numberToStartAt   = fizzbuzz_params[:starts_at].to_i()
    resultsPerPage    = (fizzbuzz_params[:per_page]  || RESUTLSPERPAGE).to_i()
    pageNumber        = (fizzbuzz_params[:page]      || numberToStartAt/resultsPerPage + 1 ).to_i() -1
    numberToEndAt     = (fizzbuzz_params[:end_at]    || HIGHESTNUMBER).to_i()

    # Page by page
    numberToStartAtOnPage   = pageNumber * resultsPerPage
    numberToEndAtOnPage     = pageNumber * resultsPerPage + resultsPerPage
    # numberToEndAtOnPage must be less than end_at so requests don't fetch more than they need too
    numberToEndAtOnPage = numberToEndAtOnPage > numberToEndAt ? numberToEndAt : numberToEndAtOnPage
    numberToStartAtOnPage = numberToStartAtOnPage > numberToStartAt ? numberToStartAtOnPage : numberToStartAt

    fizzBuzzArr = fizzBuzzObj
      .fizzBuzzArr( numberToStartAtOnPage , numberToEndAtOnPage -1 )

    render json:fizzBuzzArr, status: 200

  end

  private
  def fizzbuzz_params
    params.permit(:page,:end_at,:starts_at,:per_page)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/favourites_controller.rb
require 'will_paginate/array'

class FavouritesController < ApplicationController
  before_action :set_favourite, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  require 'fizzbuzz'

  # Set defaults for fizzBuzz
  RESUTLSPERPAGE = 100
  HIGHESTNUMBER = 100000000000
  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = Favourite.all
    fizzBuzzObj = FizzBuzz.new
    # Create a hash so favourites can be loaded by view
    @FavouriteFizz = {}
    @favourites.each do |favourite|
      @FavouriteFizz[favourite.fnumber] = favourite
    end

    # Parameterized loading or default settings
    numberToStartAt   = favourite_params[:starts_at].to_i()
    resultsPerPage    = (favourite_params[:per_page]  || RESUTLSPERPAGE).to_i()
    pageNumber        = (favourite_params[:page]      || numberToStartAt/resultsPerPage + 1 ).to_i() -1
    numberToEndAt     = (favourite_params[:end_at]    || HIGHESTNUMBER).to_i()

    # Page by page
    numberToStartAtOnPage   = pageNumber * resultsPerPage
    numberToEndAtOnPage     = pageNumber * resultsPerPage + resultsPerPage
    # numberToEndAtOnPage must be less than end_at so requests don't fetch more than they need too
    numberToEndAtOnPage = numberToEndAtOnPage > numberToEndAt ? numberToEndAt : numberToEndAtOnPage
    numberToStartAtOnPage = numberToStartAtOnPage > numberToStartAt ? numberToStartAtOnPage : numberToStartAt

    fizzBuzzArr = fizzBuzzObj
      .fizzBuzzArr( numberToStartAtOnPage , numberToEndAtOnPage -1 )

    @fizzbuzz = fizzBuzzArr.paginate(
      :page => params[:page],
      :per_page => resultsPerPage,
      :total_entries => numberToEndAt/resultsPerPage
      ).replace(fizzBuzzArr)
  end

  # POST /favourites
  # POST /favourites.json
  def create
    new_favourite_number = favourite_params[:numberToFavourite]
    @favourite = Favourite.new(fnumber:new_favourite_number)
    @favourite.save
    redirect_to_back
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite.destroy
    redirect_to_back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourite_params
      params.permit(:fnumber,:numberToFavourite,:page,:end_at,:per_page,:starts_at)
    end

    def redirect_to_back(default = root_url)
      if request.env["HTTP_REFERER"].present? && request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
        redirect_to :back
      else
        redirect_to default
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourite_api_helper.rb
module FavouriteApiHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/fizzbuzz_api_helper.rb
module FizzbuzzApiHelper
end

app/views/favourites/_form.html.erb
<%= form_for(favourite) do |f| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fnumber %>
    <%= f.text_field :fnumber %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>FizzBuzz App</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th>FizzBuzz</td>
      <th>Is a Favourite?</td>
      <th>Create/Remove</td>
    </tr>
  </thead>

  <tbody>
    <%@fizzbuzz.each do |index,fizzbuzz| %>

      <tr>
        <td><%= index%></td>
        <td><%= fizzbuzz %></td>
        <td><%= @FavouriteFizz[index.to_i].nil? ? fav=false : fav=true %></td>
        <td>
          <% if !fav %>
            <%= link_to 'New Favourite', favourites_path(numberToFavourite: index.to_i), method: :post%>
          <%else%>
            <%= link_to 'Destroy', @FavouriteFizz[index.to_i], method: :delete, data: { confirm: 'Are you sure?' } %>
          <%end%>
        </td>
      </tr>

    <% end %>
  </tbody>

</table>

<div class="center">
   <%= will_paginate @fizzbuzz %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FizzBuzzRR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>